# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Multipath TCP <br />for Linux
email: mptcp@lists.linux.dev
description: >- # this means to ignore newlines until "baseurl:"
  Multipath TCP (MPTCP) for Linux, an extension to TCP that enhances connection
  redundancy and performance by utilizing multiple underlying TCP sessions
  simultaneously. This site provides installation guides, debugging tools, FAQs,
  and a list of apps supporting MPTCP, aimed at facilitating the adoption and
  implementation of MPTCP for Linux users and developers.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mptcp.dev" # the base hostname & protocol for your site, e.g. http://example.com

theme: just-the-docs
favicon_ico: "/assets/mptcp_logo.svg"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.9.0"

# Aux links for the upper right navigation
aux_links:
  "Improve this website":
    - "//github.com/multipath-tcp/mptcp.dev"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

callouts:
  warning:
    title: Warning
    color: red

  note:
    title: Note
    color: blue

  info:
    title: Info
    color: green
